### ISSUE TITLE
问一下 坐标是怎么算出来的，？需要什么工具

### ISSUE THREAD

**Issue by 11231943** [karonl/InDoorSurfaceView#10]
这个很赞！。想问一下坐标是怎么测量出来的

**Comment by karonl** [comment]
感谢你的认可。坐标是左上角的相对坐标，也是图片本身像素点所在的坐标，目前可以使用制图工具轻易量出。
我自己使用h5开发了坐标导出工具，但目前还没整理好开源。同时，Indoorview 也在做内存优化，将会一起发布。
