### ISSUE TITLE
请问：覆盖在图片上面的区域坐标如何跟图片保持一致？有什么工具可以获取到区域的顶点坐标吗？

### ISSUE THREAD

**Issue by mengxiabing** [karonl/InDoorSurfaceView#7]
请问：覆盖在图片上面的区域坐标如何跟图片保持一致？有什么工具可以方便的获取到不同区域的顶点坐标吗？另外缩放操作是否对坐标数值有影响？

**Comment by mengxiabing** [comment]
另外手机分辨率不同或者DPI不同，可以使用相同的坐标吗？可以适配不同屏幕吗？

**Comment by karonl** [comment]
覆盖区域的坐标为图片相对坐标，点(x:10,y:10) 指的是图片上的10个像素的距离；Demo 里的 JSON 是通过我另外做的一个工具导出的，通常 PhotoShop 也能做到。缩放、手机分辨率、DPI都适配了，可以用同一套坐标和图片。

**Comment by mengxiabing** [comment]
![image](https://cloud.githubusercontent.com/assets/18475448/25890354/baf963a2-359f-11e7-8af2-b3440a4c78d4.png)
感谢回复，经过测试，PS中取的像素点和Demo 里的 JSON坐标一致。
另外请问下，DEMO中图片拖动没有边界限制，如何限制拖动的边界啊？我对canvas一知半懂，想请教下这个问题，谢谢。

**Comment by mengxiabing** [comment]
![image](https://cloud.githubusercontent.com/assets/18475448/25890626/c9f9e934-35a0-11e7-9b1d-0c986cea1456.png)
另外，退出DEMO报如上图错误：
                                         --------- beginning of crash
05-10 16:48:36.095 12664-12712/? E/AndroidRuntime: FATAL EXCEPTION: Thread-1299
                                                   Process: com.chuanmo.indoorsample, PID: 12664
                                                   java.lang.IllegalArgumentException: canvas object must be the same instance that was previously returned by lockCanvas
                                                       at android.view.Surface.unlockCanvasAndPost(Surface.java:268)
                                                       at android.view.SurfaceView$4.unlockCanvasAndPost(SurfaceView.java:860)
                                                       at com.karonl.instance.Unit.DrawThread.showBit(DrawThread.java:76)
                                                       at com.karonl.instance.Unit.DrawThread.run(DrawThread.java:40)

**Comment by mengxiabing** [comment]
surfaceHolder.unlockCanvasAndPost(c);
修改为：
if (c != null) {
                    surfaceHolder.unlockCanvasAndPost(c);
                }
不再出现上个问题中的BUG。

**Comment by karonl** [comment]
我换了逻辑，还以为不会出现这个问题，近几次提交去掉了判断，回去调一下。边界问题可以在渲染时 c.drawBitmap 对坐标进行判断，修改坐标。

**Comment by luchuantao** [comment]
楼主 能更新一版 加载矢量地图的版本吗

**Comment by xingjiyihao** [comment]
楼主能分享一下获取坐标的那个工具吗

**Comment by karonl** [comment]
@xingjiyihao 获取坐标很容易，用 PS 即可，工具我会整理放出。
@luchuantao 后期有计划读取矢量图，目前正更新 bitmap 新的读取方式，以节约内存使用。矢量图和位图在渲染上区别很大，实用性上来讲，位图表象能力更强。
